name: Deployment_workflow
on:
    push:
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install kubectl CLI
              id: install-kubectl
              uses: Azure/setup-kubectl@v5.0.0
              with:
                version: 'v1.35.0'

            - name: Set kubeConfig
              uses: Azure/k8s-set-context@v5.0.0
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}

            # - name: Setup Minikube
            #   uses: manusa/actions-setup-minikube@v2.16.1
            #   with:
            #     minikube version: 'v1.38.1'
            #     kubernetes version: 'v1.35.2'
            #     github token: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Check kubectl installition
              run: |
                  kubectl version 
                  echo "___________________________________________________________________"
                  kubectl get nodes
            # - name: Minikube status
            #   run: minikube status

            # - name: Wait for cluster
            #   run: |
            #        kubectl wait --for=condition=Ready nodes --all --timeout=120s

            # - name: Run nginx pod
            #   run: |
            #       kubectl run nginx-pod --image nginx
            #       kubectl get pods

            

             