name: docker-workflow
on:
    push:
jobs:
    docker-login:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Docker Login
              uses: docker/login-action@v4.1.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}