name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
     - main
     - feature/*

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Node JS Version
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Dependencies
      run: npm install
    - name: Run unit testing
      run: npm test
    - name: Archive Test Result
      uses: actions/upload-artifact@v7
      with:
          name: Mocha-Test-Result
          path: test-result.xml



